#!/usr/bin/env bash
# Generate the Ansible inventory from provisioned VMs.
# Reads stdin lines: "<short> <name> <host> <port>"
# Writes ansible/inventory/hosts.generated.yaml
# Kept compatible with the bash 3.2 that ships with macOS (no associative arrays).
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

load_config
mkdir -p "$(dirname "$INVENTORY_FILE")"

# Buffer stdin so we can iterate it twice (hosts, then group).
rows="$(cat)"
{
  echo "# Generated by scripts/gen-inventory.sh. Do not edit by hand."
  echo "all:"
  echo "  vars:"
  echo "    ansible_user: ${LAB_USER}"
  echo "    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
  echo "  hosts:"
  while read -r short name host port; do
    [[ -z "$short" ]] && continue
    echo "    ${short}:"
    echo "      ansible_host: ${host}"
    echo "      ansible_port: ${port}"
    echo "      vm_name: ${name}"
  done <<<"$rows"
  echo "  children:"
  echo "    role_attacker:"
  echo "      hosts:"
  while read -r short name host port; do
    [[ -z "$short" ]] && continue
    echo "        ${short}:"
  done <<<"$rows"
} > "$INVENTORY_FILE"
ok "Inventory written: ${INVENTORY_FILE}"
